### ISSUE TITLE
Unsupported URL error

### ISSUE THREAD

**Issue by teamspoad** [knamit01/ytd-gtk#4]
-------scenario, 
3 sites, a1.com--b2.com--3c.com.

a1 is main site, it has a video link embedded from b2.com in one link, and 3c.com in another link.

Everytime ytd-gtk finds a1.com/embedded-link-from-2b.com it gives an error.
Everytime ytd-gtk finds a1.com/embedded-link-from-3c.com or 4d+ and so on, no problems.

I can go onto the a1.com/embedded-link-from-2b.com and hit play and watch it just the same as the 3c links.
---------------------------------------------end of scenario

-----------------------------------------FOUND THIS AFTER RESEARCHING, I don't know how to code------

I can run this curl, grep to get the link I need, and can paste that result into your ytd-gtk, and then it works (IN SHORT, IT IS THE LINK FOLLOWING "data-origin-source=" ) : 

curl a1.com/embedded-link-from-2b.com 2>&1 | grep -o -E 'data-origin-source="([^"#]+)"' | cut -d'"' -f2

then I highlight-copy the result in terminal, ctrl-v into ytd-gtk, and it works after I do that.

even more research and I compiled all of the errored URLs from your app in a txt file, 1 url per line and ran:

cat LISTOFURLS.txt | parallel curl -L {} {/} 2>&1 | grep -o -E 'data-origin-source="([^"#]+)"' | cut -d'"' -f2 >> TEXTFILE.txt 

This gave me a list of useable URLs in a textfile (from data-origin-source) that I was unable to figure out how to run all at once from your app, and found I could with pasting into youtube-DLG.
------------------------end of research

REQUEST 1 of 2------- truly important, other is less important-----

options available on errored links that may fix the problem.  (maybe include option to look for data-origin-source tags, and others, and maybe even allow custom search commands). 

REQUEST 2 of 2------------

I could get the .ytd-gtk/urlist loaded with the names needed with a curl command output to that file, but couldn't get ytd to load that.  It would be nice to load from a file, as well as info on adding url to ytd-ytk from command, or piping from a curl/grep approach.

**Comment by Experimenter** [comment]
ytd-gtk is just a gui for youtube-dl, the aim of the project was to make downloading videos simple by providing a copy-paste/drag-drop approach to ease the process of queuing and controlling downloads with operations like pausing, reshuffling etc and to make it easy with limited graphical options without having to drop to command line. 
The first request hence is out of purview of this software, your issue will be better addressed by upstream youtube-dl maintainers.
Your second request we will try to accommodate it, by providing url queuing from a text file, in the new rewrite of the software vido (https://github.com/Experimenter/vido) which is based on python3/gtk+/gobject as opposed to current python2/gtk/pygtk.
In the meantime, since you are comfortable with cli, you can use youtube-dl which allows you to download all urls from a text file. 
We apologise for the delay in reply, we were caught up in other tasks and failed to respond timely.
